import type { Metadata } from 'next'
import { Plus_Jakarta_Sans } from 'next/font/google'
import './globals.css'

export const roboto = Plus_Jakarta_Sans({ 
  weight: '400', 
  preload: false,
})

export const metadata: Metadata = {
  title: 'JeremiasArrieta Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased dark:bg-gray-800`} >{children}</body>
    </html>
  )
}
