import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'JeremiasArrieta Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='dark:bg-gray-800'>{children}</body>
    </html>
  )
}
