import React from 'react';
import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';
import './globals.css';

// Define la fuente roboto
const roboto = Plus_Jakarta_Sans({ 
  weight: '400', 
  preload: false,
});

// Define el Layout
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased dark:bg-gray-800`}>
        {children}
      </body>
    </html>
  );
}

// Define los metadatos de la aplicación
export const metadata: Metadata = {
  title: 'JeremiasArrieta Portfolio',
  description: 'Generated by create next app',
};
